### ISSUE TITLE
Add Redux

### ISSUE THREAD

**Issue by ai** [igoradamenko/awesome-made-in-russia#2]
I think Redux can be added since it was written when Dan was in Russian.

Also, I think it will be nice to clarify what is “made in Russia”. I think the best definitions: “the project where the main maintainer was born in Russia or self-indicate themself as a part of Russian etnicity”.

**Comment by igoradamenko** [comment]
Yeah, I was thinking about being more... polite? correct? non-harmful? about defining “Russian projects”.

Not sure how to note the fact that the point of the repo is to spread kind proud between Russian community, but not aggression.

**Comment by igoradamenko** [comment]
https://github.com/igoradamenko/awesome-made-in-russia/commit/12ccb363913f1533532ef54c6508fc6ec894b507

> The project was created by the developer born in Russia or self-indicate themself as a part of Russian ethnicity.

@ai, what do you think?

**Comment by ai** [comment]
> Yeah, I was thinking about being more... polite? correct? non-harmful? about defining “Russian projects”.

“Made by Russian”. Also, we can clarify that the goal of the project is to highlight how modern IT is a product of global culture. There are many different nations in your `package-lock.json` (and we are highlighting the Russian part just because we are knowing it best).

**Comment by ai** [comment]
> 12ccb36

👍

**Comment by igoradamenko** [comment]
Added Redux: https://github.com/igoradamenko/awesome-made-in-russia/commit/384e66ee65be484bf4303534d39b6c30f7b280e4

> the goal of the project is to highlight how modern IT is a product of global culture. There are many different nations in your package-lock.json (and we are highlighting the Russian part just because we are knowing it best).

Added this line: https://github.com/igoradamenko/awesome-made-in-russia/commit/1109b459c73577464aca397f2738df8804868462

Thanks!

Feel free to close the issue if you think it's solved.
