### ISSUE TITLE
Improve Effector description

### ISSUE THREAD

**Issue by igoradamenko** [igoradamenko/awesome-made-in-russia#4]
We prefer to add authors' name and surname instead of just nicknames, but we don't know @zerobias surname and can't find it anywhere.

If it's not a secret and someone (@zerobias himself?) can disclosure it, it would be great!

**Comment by zerobias** [comment]
I am Dmitry Boldyrev. 

It's nice to see my project on that list, thank you 😊

**Comment by igoradamenko** [comment]
Fixed: https://github.com/igoradamenko/awesome-made-in-russia/commit/f326db7f145a4e57da6c29b18b02f86fec6866bd

@zerobias, well, thank you for Effector! 👍
